### PR TITLE
Inline comments in .travis.yml for CACHIX_CACHE/NUR_REPO

### PR DESCRIPTION
**Pull request by kolloch**
During setup, I wondered what the format of this variables is.  While
searching for sample values, I noticed that people use these
inconsistently. So better be explicit.

I removed the paragraph from the README.md to avoid duplication.

### CODE REVIEW

**Comment by fgaz** [comment]
Could you keep the newlines at the end of the files (\n\n -> \n at the end of the readme is ok)?

**Comment by kolloch** [comment]
Sure.

Not arguing but why? I might learn something. I just configured my editor to through away these things so I don't have to think about it anymore but perhaps I have to.

Thanks for the template!

**Comment by fgaz** [comment]
@kolloch 

Other than adhering to the same format as nixpkgs, it's mostly personal preference (like most syntax stuff, tabs vs spaces etc). I guess it boils down to "a line being a sequence of characters terminated by a newline" vs "a line is a sequence of non-newlines, and lines are separated by a newline". The former just makes the most sense to me. It also has some advantages, like not messing up the shell prompt when outputting a file to the terminal, making copy/paste consistent in some editors, and being able to concatenate files by just appending them (not that it matters when writing nix).

**Comment by kolloch** [comment]
That makes sense. Thanks for answering.

**Pull request merged**
